import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { connectDB } from "@/util/database"; // database.js 파일 import

const inter = Inter({ subsets: ["latin"] });

export default function Home({ result }) {
  // Home 컴포넌트 함수에 result props 추가
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        (생략)
        <div className={styles.grid}>
          // DB에서 가져온 값을 화면에 보여줌
          {result.map((data) => (
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
              key={data.title}
            >
              <h2>
                {data.title} <span>-&gt;</span>
              </h2>
              <p> {data.content}</p>
            </a>
          ))}
          (생략)
        </div>
      </main>
    </>
  );
}

// getServerSideProps 함수 추가 및 DB 데이터 가져옴
export async function getServerSideProps() {
  const client = await connectDB;
  const db = client.db("vercel-test"); // db는 여러분의 db로 변경해주세요.
  const result = await db
    .collection("products") // collection 이름도 여러분의 collection명으로 변경해주세요.
    .find({}, { projection: { _id: 0 } })
    .toArray();

  return {
    props: {
      result: JSON.parse(JSON.stringify(result)),
    },
  };
}
